services:
  - type: web
    name: terra-sr
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8080
      - key: COPERNICUS_CLIENT_ID
        sync: false
      - key: COPERNICUS_CLIENT_SECRET
        sync: false
      - key: CARTO_API_KEY
        sync: false
